sudo: false
language: node_js
node_js:
  - 9.3.0
env:
  global:
    - YARN_VERSION=1.3.2

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

install:
  - yarn install --pure-lockfile

script:
  - yarn run eslint
  - ./node_modules/.bin/lerna run test
  # - yarn run flow

after_success:
  - ./node_modules/.bin/codecov

cache:
  yarn: true
  directories:
    - "~/.yarn"
    - node_modules

notifications:
  email: evenchange4@gmail.com
