// flow-typed signature: dd632f3b1a33e0dd67bc30cbe55fa7db
// flow-typed version: <<STUB>>/@todomvc-subscriptions/constants_v^1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@todomvc-subscriptions/constants'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@todomvc-subscriptions/constants' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@todomvc-subscriptions/constants/actions' {
  declare module.exports: any;
}

declare module '@todomvc-subscriptions/constants/clientID' {
  declare module.exports: any;
}

// Filename aliases
declare module '@todomvc-subscriptions/constants/actions.js' {
  declare module.exports: $Exports<'@todomvc-subscriptions/constants/actions'>;
}
declare module '@todomvc-subscriptions/constants/clientID.js' {
  declare module.exports: $Exports<'@todomvc-subscriptions/constants/clientID'>;
}
